jobs:
  - job: job_${{ parameters.platform }}_${{ parameters.versionSpec }}_${{ parameters.architecture }}
    displayName: ${{ parameters.platform }} ${{ parameters.versionSpec }} ${{ parameters.architecture }}
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        2.7:
          versionSpec: '2.7'
          architecture: 'x64'
        3.4:
          versionSpec: '3.4'
          architecture: 'x64'
        3.5:
          versionSpec: '3.5'
          architecture: 'x64'
        3.6:
          versionSpec: '3.6'
          architecture: 'x64'
        3.7:
          versionSpec: '3.7'
          architecture: 'x64'
    steps:
      - bash: |
          echo "      This environment: |${{ parameters.platform }}-$(versionSpec)-$(architecture)"
          echo "Requested environments: ${{ parameters.environments }}"
          if [[ "${{ parameters.environments }}" != *"|${{ parameters.platform }}-$(versionSpec)-"* ]]; then echo '##vso[task.setvariable variable=agent.jobstatus;]Skipped'; echo '##vso[task.complete result=Canceled;]DONE'; fi
        displayName: Skip if not requested
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(versionSpec)
          architecture: $(architecture)
      - template: ../steps/in_archive_from_artifact.yml
      - bash: |
          ${{ parameters.command }}
        displayName: Run Command
      - task: CopyFiles@2
        inputs:
          contents: 'requirements/*.txt'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: lock_files
