jobs:
- job: run_command
#  condition: contains(dependencies.BOOTS_ENVIRONMENTS.outputs['v.v'], format('|{}', variables['environment']))
  dependsOn: BOOTS_ENVIRONMENTS
  displayName: $(displayName)
  pool:
    vmImage: $(vmImage)
  steps:
  - task: UsePythonVersion@0
    inputs:
      architecture: $(architecture)
      versionSpec: $(versionSpec)
  - template: ../steps/in_archive_from_artifact.yml
  - bash: $(BOOTS_COMMAND)
    displayName: Run Command
  - task: CopyFiles@2
    inputs:
      contents: requirements/*.txt
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: results
      pathToPublish: $(Build.ArtifactStagingDirectory)
  strategy:
    matrix:
      ${{ if contains('|Linux_3.6-x64', '|Linux_3.6-x64') }}:
        force_linux_python_3_6_x64:
          architecture: x64
          displayName: 'force_Linux: Python 3.6-x64'
          environment: force_Linux_3.6-x64
          job: force_linux_python_3_6_x64
          platform: force_Linux
          versionSpec: '3.6'
          vmImage: ubuntu-16.04
      ${{ if contains(dependencies.BOOTS_ENVIRONMENTS['v.v'], '|Linux_3.6-x64') }}:
        linux_python_3_6_x64:
          architecture: x64
          displayName: 'Linux: Python 3.6-x64'
          environment: Linux_3.6-x64
          job: linux_python_3_6_x64
          platform: Linux
          versionSpec: '3.6'
          vmImage: ubuntu-16.04
      ${{ if contains(dependencies.BOOTS_ENVIRONMENTS['v.v'], '|Linux_3.7-x64') }}:
        linux_python_3_7_x64:
          architecture: x64
          displayName: 'Linux: Python 3.7-x64'
          environment: Linux_3.7-x64
          job: linux_python_3_7_x64
          platform: Linux
          versionSpec: '3.7'
          vmImage: ubuntu-16.04
      ${{ if contains(dependencies.BOOTS_ENVIRONMENTS['v.v'], '|Windows_3.6-x64') }}:
        windows_python_3_6_x64:
          architecture: x64
          displayName: 'Windows: Python 3.6-x64'
          environment: Windows_3.6-x64
          job: windows_python_3_6_x64
          platform: Windows
          versionSpec: '3.6'
          vmImage: vs2017-win2016
      ${{ if contains(dependencies.BOOTS_ENVIRONMENTS['v.v'], '|Windows_3.7-x64') }}:
        windows_python_3_7_x64:
          architecture: x64
          displayName: 'Windows: Python 3.7-x64'
          environment: Windows_3.7-x64
          job: windows_python_3_7_x64
          platform: Windows
          versionSpec: '3.7'
          vmImage: vs2017-win2016
      ${{ if contains(dependencies.BOOTS_ENVIRONMENTS['v.v'], '|macOS_3.6-x64') }}:
        macos_python_3_6_x64:
          architecture: x64
          displayName: 'macOS: Python 3.6-x64'
          environment: macOS_3.6-x64
          job: macos_python_3_6_x64
          platform: macOS
          versionSpec: '3.6'
          vmImage: macOS-10.13
      ${{ if contains(dependencies.BOOTS_ENVIRONMENTS['v.v'], '|macOS_3.7-x64') }}:
        macos_python_3_7_x64:
          architecture: x64
          displayName: 'macOS: Python 3.7-x64'
          environment: macOS_3.7-x64
          job: macos_python_3_7_x64
          platform: macOS
          versionSpec: '3.7'
          vmImage: macOS-10.13
