jobs:
  - job: lock_${{ parameters.platform }}_${{ parameters.versionSpec }}_${{ parameters.architecture }}
    displayName: Lock ${{ parameters.platform }} ${{ parameters.versionSpec }} ${{ parameters.architecture }}
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        3.6:
          versionSpec: '3.6'
          architecture: 'x64'
    steps:
      - bash: |
          echo "|${{ parameters.platform }}-$(versionSpec)-"
          echo "${BOOTS_ENVIRONMENTS}"
          if [[ "${BOOTS_ENVIRONMENTS}" != *"|${{ parameters.platform }}-$(versionSpec)-"* ]]; then echo '##vso[task.setvariable variable=agent.jobstatus;]Skipped'; echo '##vso[task.complete result=Canceled;]DONE'; fi
        displayName: Skip if not requested
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(versionSpec)
          architecture: $(architecture)
      - template: ../steps/in_archive_from_artifact.yml
      - bash: |
          ${{ parameters.command }}
        displayName: Lock
      - task: CopyFiles@2
        inputs:
          contents: 'requirements/*.txt'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: lock_files
